[[plugins]]
repo='lervag/vimtex'
on_ft=['tex']
hook_source='''
  let g:vimtex_view_general_viewer = 'sumatraPDF.exe'
  let g:vimtex_view_general_options = '-reuse-instance @pdf'
  let g:vimtex_view_general_options_latexmk = '-reuse-instance'
'''

[[plugins]]
repo='iamcco/markdown-preview.nvim'
on_ft=['markdown', 'pandoc.markdown', 'rmd']    
hook_source='''
  let g:mkdp_open_ip = '6789'
'''

[[plugins]]
repo='Zaptic/elm-vim'
on_ft=['elm']
hook_source='''
  let g:elm_setup_keybindings = 0
'''
